### ISSUE TITLE
Resharper 9 support

### ISSUE THREAD

**Issue by reitzmichnicht** [hmemcpy/AgentMulder#67]
Please upgrade your great plugin to support Resharper 9
Thanks in advance

Michael

**Comment by petemounce** [comment]
+1! :)

**Comment by rog1039** [comment]
That would be great!

**Comment by mamodom** [comment]
+1

**Comment by khellang** [comment]
:+1:

**Comment by drphrozen** [comment]
:+1:

**Comment by sobek1985** [comment]
:+1:

**Comment by vicero** [comment]
:+1:

**Comment by chrisaut** [comment]
:+1:

**Comment by hmemcpy** [comment]
I'm happy to say that after a lot of hard work (and much needed help), Mulder for R# 9 is finally a thing!
Please go to your Extension Manager and look for it there!

Thank you for your patience!

**Comment by mamodom** [comment]
:+1:
