### ISSUE TITLE
Cannot install - Not found in the Extension Manager

### ISSUE THREAD

**Issue by Sergey-Terekhin** [hmemcpy/AgentMulder#79]
Hi,
I cannot find AgentMudler in the Resharper's Extension Manager

**Comment by hmemcpy** [comment]
Hi, what version of ReSharper are you using? I still haven't updated it to 9.2, I'm afraid...

**Comment by Sergey-Terekhin** [comment]
Hi,
I use version 9.2 :(


2015-08-06 10:56 GMT+03:00 Igal Tabachnik <notifications@github.com>:

> Hi, what version of ReSharper are you using? I still haven't updated it to
> 9.2, I'm afraid...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hmemcpy/AgentMulder/issues/79#issuecomment-128282969>.
>



-- 
С уважением!                                    Sincerely,
Терехин Сергей                                 Sergey Terekhin

mob: +7 926 1433057

**Comment by hmemcpy** [comment]
Just published a 9.2 compatible version, please check the extension manager again!
